### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by RandomBrown** [nccgroup/Winpayloads#13]
In Kali Linux 2016.2:
# ./setup.sh

[_] Installing Dependencies 
Obj:1 http:[...]
[...]
[_] Grabbing Wine Modules 
wine: cannot find '/root/.wine/drive_c/Python27/Scripts/pip.exe'
[*] Done 

if now run:
# ./setup.sh -r

[...]
[_] Installing Python Requirements 
Requirement already satisfied (use --upgrade to upgrade): blessings in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.7/dist-packages
[_] Installing Pyinstaller 
[*] Remove /opt/pyinstaller? [Y/n] 

\033[1;31m[*] Reinstall Cancelled \033[0m

**Comment by Charliedean** [comment]
Hi,
This is because pyinstaller needs to be removed to fully reinstall winpayloads.

If you say no the setup with exit

**Comment by RandomBrown** [comment]
Sorry, but there is an error in the wine installation:
[] Grabbing Wine Modules
wine: cannot find '/root/.wine/drive_c/Python27/Scripts/pip.exe'

and when he asks:
[_] Remove /opt/pyinstaller? [Y/n]
pulse the 'Y' key (default) and you get the error:
\033[1;31m[_] Reinstall Cancelled \033[0m

the error out pressing 'Y' or pressing 'N'.

**Comment by Charliedean** [comment]
Try a lowercase 'y'
