### ISSUE TITLE
Error of launch generator payload

### ISSUE THREAD

**Issue by PentestinGxRoot** [nccgroup/Winpayloads#16]
[*] Creating Payload using Pyinstaller...
mv: can not evaluate dist / payload.exe ': No such file or folder like this

[*] Has Been Generated Payload.exe And Is Located Here: /etc/winpayloads/Windows_Meterpreter_Reverse_Shell.exe
rm: can not remove 'dist': No such file or folder like this
rm: can not remove 'build': No such file or folder like this
rm: can not remove \* spec ': No such file or folder like this

picture url: [image.prntscr.com/image/4c366d979c864549a34d0b3464a48c13.png](url)

Help me bro

**Comment by Charliedean** [comment]
Hi,
Could you try running ./setup.sh -r to reinstall winpayloads.
Let me know if there are any errors during install.

Thanks.

**Comment by PentestinGxRoot** [comment]
I installed and here's the news.

[http://pastebin.com/raw/yJhiBvbc](url)

first error : **"wine: cannot find '/root/.wine/drive_c/Python27/python.exe'"**
two errors: `err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found`

you can watch the pastebin link please.

**Comment by Charliedean** [comment]
Hi,

Could you run these commands:
updatedb
Locate python.exe

Let me know the output.

Thanks

**Comment by PentestinGxRoot** [comment]
updatedb
Locate python.exe
bash: Locate: command not found /D

**Comment by Charliedean** [comment]
Try Lowercase 
locate

**Comment by PentestinGxRoot** [comment]
sorry

locate python.exe
/root/.config/wine/veil/drive_c/Python27/python.exe
/root/.wine/drive_c/Python27/python.exe

**Comment by Charliedean** [comment]
Hi,

The error from the install reads it cannot find "/root/.wine/drive_c/Python27/python.exe" but the command you just ran shows that the windows python executable is in the right directory.
Therefore I do not understand why it is not working correctly.

I also see that veil has been installed. This could be conflicting with winpayloads as both run windows python executables.

You may have to install winpayloads on a new OS.

Sorry I couldn't help.

**Comment by legendary77** [comment]
how remove windowspayload ? 

Thank you bro

**Comment by PentestinGxRoot** [comment]
I'll get the error and correct thank you

**Comment by PrettyBoyPBM** [comment]
Netw0rklan did you fixed? i have the same problem ;c
