### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by martingonzalez123** [nccgroup/Winpayloads#17]
i get this error
fatal: Ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git

When i try to update i can't and anyways when i create the backdoor show me error too..

**Comment by martingonzalez123** [comment]
with dns it's impossible :(

**Comment by martingonzalez123** [comment]
[*] Upload To Local Websever or (p)sexec? [y]/p/n: n
Traceback (most recent call last):
  File "./WinPayloads.py", line 46, in <module>
    getAndRunMainMenu()
  File "/root/Bureau/winpayloads/lib/menu.py", line 61, in getAndRunMainMenu
    mainMenu.runmenu()
  File "/root/Bureau/winpayloads/lib/menu.py", line 115, in runmenu
    result = extrawork(payloadchoice,payload)
  File "/root/Bureau/winpayloads/lib/preparepayload.py", line 111, in dnsPayloadGeneration
    startHttpsMetasploit(portnum,DNSaddr)

**Comment by Omardavinci** [comment]
con ip me ha funcionado con dns hasta el momento no bueno muchas gracias!

**Comment by Omardavinci** [comment]
tampoco parece conectar

**Comment by martingonzalez123** [comment]
solo dns con ip resuelve

**Comment by martingonzalez123** [comment]
with armitage dont work.

**Comment by Charliedean** [comment]
Should be fixed in latest commit
