### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by developerehis** [nccgroup/Winpayloads#19]
Hello,

I am trying to install Winpayloads on my kali machine but it seems to have failed and i get the following error:

[*] Installing Python Requirements 
Requirement already satisfied: blessings in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyasn1 in /usr/lib/python2.7/dist-packages
[*] Installing Pyinstaller 
[*] Installed Already, Skipping! 
[*] Downloading Python27, Pywin32 and Pycrypto For Wine 
[*] Installed Already, Skipping! 
[*] Installing impacket from Git 
[*] Installed Already, Skipping! 
[*] Grabbing Wine Modules 
wine: cannot find '/root/.wine/drive_c/Python27/Scripts/pip.exe'
[*] Done 
[*] Grabbing Modules 
rm: cannot remove 'psexecspray.py': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4698  100  4698    0     0   2282      0  0:00:02  0:00:02 --:--:--  2283
[*] Done 
[*] Grabbing Certs 
Generating RSA private key, 2048 bit long modulus
...............+++
...................+++
e is 65537 (0x10001)
writing RSA key
Signature ok
subject=/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com
Getting Private key
[*] Done 
[*] Cleaning Up 
[*] Done 

Even when i went ahead to try creating payloads i get this error too:

Traceback (most recent call last):
  File "/opt/pyinstaller/pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\pyinstaller\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\pyinstaller\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\pyinstaller\PyInstaller\depend\bindepend.py", line 26, in <module>
    from . import dylib, utils
  File "Z:\opt\pyinstaller\PyInstaller\depend\utils.py", line 25, in <module>
    from ..lib.modulegraph import modulegraph
  File "Z:\opt\pyinstaller\PyInstaller\lib\modulegraph\modulegraph.py", line 18, in <module>
    import pkg_resources
ImportError: No module named pkg_resources

Kindly assist.

Thanks

**Comment by Charliedean** [comment]
Hi,
Could you please try to run the setup.sh -r to reinstall, and select yes to
uninstall pyinstaller.

Thanks
Charlie

**Comment by developerehis** [comment]
Thanks,

It worked just fine now. I want to know more about how the persistence work. Cos i intend to use meterpreter session from Armitage. Once the payload executes on the target machine, doe ths means the persistence is automatically activated?

Or i have to manipulate things from meterpreter session before this can work?

**Comment by Charliedean** [comment]
Hi,
When you choose the persistence option. A power shell script is run on the
target machine which adds persistence to the startup folder and a registry
key. Therefore on reboot, the payload will execute and try to connect back
to your machine. Bear in mind, if your IP address changes, the payload will
not connect.

Thanks
Charlie

**Comment by developerehis** [comment]
Thanks,

Sorry i am asking so many question. reverse HTTP and Reverse TCP what are the merits and demerit of each.

I just tried reverse HTTP and i get this error from my Win 7 machine 

https://10.0.2.15:2222 handling request from 10.0.2.2; (UUID: uosap5ty) Exception handling request: Bad file descriptor

**Comment by developerehis** [comment]
One last thing. The software for masking my payload to look like pdf or other documents did not work with Winpayloads, Is there any recommendation from  your end?
