### ISSUE TITLE
problem while excute winpayloads 

### ISSUE THREAD

**Issue by Ahmad1995Ali** [nccgroup/Winpayloads#24]
Hi,
When i finished install winpayloads this error come out and i search many times but i couldn't fix it the error is :
root@kali:~/Desktop/Winpayloads# ./WinPayloads.py 
Traceback (most recent call last):
  File "./WinPayloads.py", line 5, in <module>
    from lib.menu import *
  File "/root/Desktop/Winpayloads/lib/menu.py", line 4, in <module>
    from generatepayload import *
  File "/root/Desktop/Winpayloads/lib/generatepayload.py", line 3, in <module>
    from psexecspray import *
  File "/root/Desktop/Winpayloads/lib/psexecspray.py", line 4, in <module>
    import blessings
ImportError: No module named blessings
Please Help Me Soon As possible With my regards .

**Comment by Charliedean** [comment]
Hi please rerun the setup as it will fix the issue.
Thanks

**Comment by Ahmad1995Ali** [comment]
I Will do it THANKS FOR your attention .

**Comment by Ahmad1995Ali** [comment]
Hi,
i re-setup it  again but it steal have same error

**Comment by Charliedean** [comment]
Did you do a git pull first?

**Comment by Ahmad1995Ali** [comment]
No i don't know how please help .

**Comment by Ahmad1995Ali** [comment]
Hi
I Search for git pull and i understand what is and do what you say and it's Working 
Thanks For Your Help.
