### ISSUE TITLE
multiple errors found during install

### ISSUE THREAD

**Issue by joselbr2099** [nccgroup/Winpayloads#3]
byte-compiling /usr/lib/python3.5/site-packages/impacket/hresult_errors.py to hresult_errors.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/smb3.py to smb3.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/smb3.py", line 234
    print "CONNECTION"
                     ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/IP6_Extension_Headers.py to IP6_Extension_Headers.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/IP6_Extension_Headers.py", line 56
    raise ImpactPacketException, "Cannot load options from truncated packet"
                               ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/NDP.py to NDP.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/spnego.py to spnego.cpython-35.pyc
Sorry: TabError: inconsistent use of tabs and spaces in indentation (spnego.py, line 77)
byte-compiling /usr/lib/python3.5/site-packages/impacket/cdp.py to cdp.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/examples/remcomsvc.py to remcomsvc.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/examples/**init**.py to **init**.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/examples/serviceinstall.py to serviceinstall.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/examples/serviceinstall.py", line 65
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/examples/logger.py to logger.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/smb3structs.py to smb3structs.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/IP6_Address.py to IP6_Address.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/IP6_Address.py", line 246
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/uuid.py to uuid.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/uuid.py", line 22
    top = (1L<<31)-1
            ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/version.py to version.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/ImpactPacket.py to ImpactPacket.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/ImpactPacket.py", line 37
    return `self.value`
           ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dns.py to dns.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dns.py", line 616
    print d
          ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/tds.py to tds.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/tds.py", line 48
    print message
                ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/pcapfile.py to pcapfile.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/**init**.py to **init**.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dhcp.py to dhcp.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dhcp.py", line 227
    print pp
           ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/structure.py to structure.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/structure.py", line 100
    print "packField( %s | %s )" % (fieldName, format)
                               ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/Dot11KeyManager.py to Dot11KeyManager.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/gssapi.py to gssapi.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/asn1.py to asn1.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/constants.py to constants.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/**init**.py to **init**.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/types.py to types.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/krb5/types.py", line 255
    print Principal("marc")
                  ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/crypto.py to crypto.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/ccache.py to ccache.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/krb5/ccache.py", line 73
    print "%sAuth : %s" % (indent, datetime.fromtimestamp(self['authtime']).isoformat())
                      ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/krb5/kerberosv5.py to kerberosv5.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/krb5/kerberosv5.py", line 134
    except KerberosError, e:
                        ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/ese.py to ese.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/ese.py", line 440
    print "%04x  " % i,
                 ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/ImpactDecoder.py to ImpactDecoder.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/nmb.py to nmb.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/nmb.py", line 457
    raise NetBIOSError, ( 'Cannot bind to a good UDP port', ERRCLASS_OS, errno.EAGAIN )
                      ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/winregistry.py to winregistry.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/winregistry.py", line 321
    print "%s%s" % (self.indent, nk['KeyName'])
               ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/wps.py to wps.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/Dot11Crypto.py to Dot11Crypto.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/scmr.py to scmr.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/scmr.py", line 1285
    except DCERPCSessionError, e:
                             ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/epm.py to epm.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/epm.py", line 1295
    if tmp_address <> '':
                    ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/sasec.py to sasec.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/mgmt.py to mgmt.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dtypes.py to dtypes.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dtypes.py", line 98
    print "%s" % msg,
             ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/drsuapi.py to drsuapi.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/drsuapi.py", line 91
    print msg,
            ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/atsvc.py to atsvc.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/samr.py to samr.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/samr.py", line 303
    print "%s" % msg,
             ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/**init**.py to **init**.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/tsch.py to tsch.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/rrp.py to rrp.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/nrpc.py to nrpc.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/srvs.py to srvs.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/srvs.py", line 1756
    print "%s" % msg,
             ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/wkst.py to wkst.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/transport.py to transport.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/transport.py", line 139
    raise RuntimeError, 'virtual function'
                      ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/enum.py to enum.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/rpcrt.py to rpcrt.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/rpcrt.py", line 122
    0x00000005L : 'rpc_s_access_denied',
              ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/lsat.py to lsat.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/ndr.py to ndr.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/ndr.py", line 159
    print "\n%s" % msg
               ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/lsad.py to lsad.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/lsad.py", line 153
    print "%s" % (msg),
             ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcomrt.py to dcomrt.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1013
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/**init**.py to **init**.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/oaut.py to oaut.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/oaut.py", line 287
    print "%s" % (msg)
             ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/wmi.py to wmi.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 843
    print "[%s]" % qualifier
               ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/scmp.py to scmp.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/scmp.py", line 304
    except DCERPCException, e:
                          ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/vds.py to vds.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/vds.py", line 201
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/v5/dcom/comev.py to comev.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dcerpc/**init**.py to **init**.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/smbconnection.py to smbconnection.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/smbconnection.py", line 214
    except (smb.SessionError, smb3.SessionError), e:
                                                ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/nt_errors.py to nt_errors.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/crypto.py to crypto.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/crypto.py", line 384
    print s[:8] ,
          ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling /usr/lib/python3.5/site-packages/impacket/ICMP6.py to ICMP6.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/eap.py to eap.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/smbserver.py to smbserver.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/smbserver.py", line 178
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/ntlm.py to ntlm.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/ntlm.py", line 238
    print "%s: {%r}" % (i,self[i])
                   ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/IP6.py to IP6.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/smb.py to smb.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/smb.py", line 632
    y = t & 0xffffffffL
                      ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python3.5/site-packages/impacket/pcap_linktypes.py to pcap_linktypes.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/helper.py to helper.cpython-35.pyc
byte-compiling /usr/lib/python3.5/site-packages/impacket/dot11.py to dot11.cpython-35.pyc
  File "/usr/lib/python3.5/site-packages/impacket/dot11.py", line 470
    crcle=crc32(bytes)&0xffffffffL
                                 ^
SyntaxError: invalid syntax

**Comment by Charliedean** [comment]
Seems like an issue with python3.5, WinPayloads depends on a lot of things that only run on python2.7

**Comment by cybernet** [comment]
Winpayloads - Python2.7

it's the 1st line from Readme file ...
big and black ...
