### ISSUE TITLE
In use encountered some problems

### ISSUE THREAD

**Issue by qsdj** [nccgroup/Winpayloads#32]
Use the setup.sh file after the installation of payload generated when the error occurs.

`Main Menu> 1

[*] Press Enter For Default Port (4444)
[*] Port>

[*] Press Enter To Get Local Ip Automatically (192.168.0.1)
[*] IP>
[*] IP SET AS 192.168.0.1
[*] PORT SET AS 4444

[*] Creating Payload using Pyinstaller ...
Mv: unable to get 'dist / payload.exe' file status (stat): no that file or directory

[*] Payload.exe Has Been Generated And Is Here Here: /home/root/winpayloads/Windows_Reverse_Shell.exe
Rm: can not delete 'dist': no that file or directory
Rm: can not delete 'build': no that file or directory
Rm: can not delete '* .spec': no that file or directory`

My system version is Ubuntu 16.04.2 LTS. thank!

**Comment by Charliedean** [comment]
Hi,
Please run setup -r and post the output

**Comment by qsdj** [comment]
Hi,
thank you for your reply
The following is the output

> Sudo ./setup.sh -r
[Sudo] x password:
[*] Installing Dependencies
Hit: 1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get: 2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get: 3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get: 4 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get: 5 http://archive.ubuntu.com/ubuntu xenial-updates / main Sources [259 kB]
Get: 6 http://archive.ubuntu.com/ubuntu xenial-updates / main amd64 Packages [578 kB]
Get: 7 http://archive.ubuntu.com/ubuntu xenial-updates / main i386 Packages [559 kB]
Get: 8 http://archive.ubuntu.com/ubuntu xenial-updates / main amd64 DEP-11 Metadata [304 kB]
Get: 9 http://archive.ubuntu.com/ubuntu xenial-updates / main DEP-11 64x64 Icons [202 kB]
Get: 10 http://archive.ubuntu.com/ubuntu xenial-updates / universe amd64 DEP-11 Metadata [163 kB]
Get: 11 http://archive.ubuntu.com/ubuntu xenial-updates / universe DEP-11 64x64 Icons [212 kB]
Get: 12 http://archive.ubuntu.com/ubuntu xenial-updates / multiverse amd64 DEP-11 Metadata [5,892 B]
Get: 13 http://archive.ubuntu.com/ubuntu xenial-backports / universe amd64 DEP-11 Metadata [4,672 B]
Get: 14 http://archive.ubuntu.com/ubuntu xenial-backports / main amd64 DEP-11 Metadata [3,328 B]
Get: 15 http://archive.ubuntu.com/ubuntu xenial-security / main amd64 DEP-11 Metadata [59.2 kB]
Get: 16 http://archive.ubuntu.com/ubuntu xenial-security / main DEP-11 64x64 Icons [54.2 kB]
Get: 17 http://archive.ubuntu.com/ubuntu xenial-security / universe amd64 DEP-11 Metadata [40.6 kB]
Get: 18 http://archive.ubuntu.com/ubuntu xenial-security / universe DEP-11 64x64 Icons [56.1 kB]
Has downloaded 2,808 kB, takes 5 seconds (476 kB / s)
Reading the package list ... finished
Reading the package list ... finished
The dependency tree of the package is being analyzed
Reading status information ... is finished
Python is already the latest version (2.7.11-1).
Unzip is the latest version (6.0-20ubuntu1).
Python-pefile is the latest version (1.2.10.139-2).
Git is already the latest version (1: 2.7.4-0ubuntu1.1).
Python-crypto is the latest version (2.6.1-6ubuntu0.16.04.2).
Python2.7 is the latest version (2.7.12-1ubuntu0 ~ 16.04.1).
Wget is already the latest version (1.17.1-1ubuntu1.2).
Winbind is the latest version (2: 4.3.11 + dfsg-0ubuntu0.16.04.9).
Python-pip is the latest version (8.1.1-2ubuntu0.4).
Upgraded 0 packages, newly installed 0 packages, 0 packages to be uninstalled, 0 packages were not upgraded.
[*] Installing Wine
Reading the package list ... finished
The dependency tree of the package is being analyzed
Reading status information ... is finished
E: Can not locate package wine32
Reading the package list ... finished
The dependency tree of the package is being analyzed
Reading status information ... is finished
Wine is already the latest version (1: 1.6.2-0ubuntu14.2).
Upgraded 0 packages, newly installed 0 packages, 0 packages to be uninstalled, 0 packages were not upgraded.
[*] Installing Python Requirements
The directory '/home/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If installed pip with sudo, you May want sudo's -H flag.
The directory '/home/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. Check the permissions and owner of that directory. If installed pip with sudo, you may want sudo's -H flag
Requirement already satisfied: blessed in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six> = 1.9.0 in /usr/lib/python2.7/dist-packages (from blessed)
Requirement already satisfied: wcwidth> = 0.1.4 in /usr/local/lib/python2.7/dist-packages (from blessed)
The directory '/home/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If installed pip with sudo, you May want sudo's -H flag.
The directory '/home/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. Check the permissions and owner of that directory. If installed pip with sudo, you may want sudo's -H flag
Requirement already satisfied: pyasn1 in /usr/lib/python2.7/dist-packages
Install the Pyinstaller
[*] Remove / opt / pyinstaller? [Y / n]

Not reinstalling ...

>

**Comment by qsdj** [comment]
Hi,
thank you for your reply
The following is the output

> Sudo ./setup.sh -r
[Sudo] x password:
[*] Installing Dependencies
Hit: 1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get: 2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get: 3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get: 4 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get: 5 http://archive.ubuntu.com/ubuntu xenial-updates / main Sources [259 kB]
Get: 6 http://archive.ubuntu.com/ubuntu xenial-updates / main amd64 Packages [578 kB]
Get: 7 http://archive.ubuntu.com/ubuntu xenial-updates / main i386 Packages [559 kB]
Get: 8 http://archive.ubuntu.com/ubuntu xenial-updates / main amd64 DEP-11 Metadata [304 kB]
Get: 9 http://archive.ubuntu.com/ubuntu xenial-updates / main DEP-11 64x64 Icons [202 kB]
Get: 10 http://archive.ubuntu.com/ubuntu xenial-updates / universe amd64 DEP-11 Metadata [163 kB]
Get: 11 http://archive.ubuntu.com/ubuntu xenial-updates / universe DEP-11 64x64 Icons [212 kB]
Get: 12 http://archive.ubuntu.com/ubuntu xenial-updates / multiverse amd64 DEP-11 Metadata [5,892 B]
Get: 13 http://archive.ubuntu.com/ubuntu xenial-backports / universe amd64 DEP-11 Metadata [4,672 B]
Get: 14 http://archive.ubuntu.com/ubuntu xenial-backports / main amd64 DEP-11 Metadata [3,328 B]
Get: 15 http://archive.ubuntu.com/ubuntu xenial-security / main amd64 DEP-11 Metadata [59.2 kB]
Get: 16 http://archive.ubuntu.com/ubuntu xenial-security / main DEP-11 64x64 Icons [54.2 kB]
Get: 17 http://archive.ubuntu.com/ubuntu xenial-security / universe amd64 DEP-11 Metadata [40.6 kB]
Get: 18 http://archive.ubuntu.com/ubuntu xenial-security / universe DEP-11 64x64 Icons [56.1 kB]
Has downloaded 2,808 kB, takes 5 seconds (476 kB / s)
Reading the package list ... finished
Reading the package list ... finished
The dependency tree of the package is being analyzed
Reading status information ... is finished
Python is already the latest version (2.7.11-1).
Unzip is the latest version (6.0-20ubuntu1).
Python-pefile is the latest version (1.2.10.139-2).
Git is already the latest version (1: 2.7.4-0ubuntu1.1).
Python-crypto is the latest version (2.6.1-6ubuntu0.16.04.2).
Python2.7 is the latest version (2.7.12-1ubuntu0 ~ 16.04.1).
Wget is already the latest version (1.17.1-1ubuntu1.2).
Winbind is the latest version (2: 4.3.11 + dfsg-0ubuntu0.16.04.9).
Python-pip is the latest version (8.1.1-2ubuntu0.4).
Upgraded 0 packages, newly installed 0 packages, 0 packages to be uninstalled, 0 packages were not upgraded.
[*] Installing Wine
Reading the package list ... finished
The dependency tree of the package is being analyzed
Reading status information ... is finished
E: Can not locate package wine32
Reading the package list ... finished
The dependency tree of the package is being analyzed
Reading status information ... is finished
Wine is already the latest version (1: 1.6.2-0ubuntu14.2).
Upgraded 0 packages, newly installed 0 packages, 0 packages to be uninstalled, 0 packages were not upgraded.
[*] Installing Python Requirements
The directory '/home/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If installed pip with sudo, you May want sudo's -H flag.
The directory '/home/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. Check the permissions and owner of that directory. If installed pip with sudo, you may want sudo's -H flag
Requirement already satisfied: blessed in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six> = 1.9.0 in /usr/lib/python2.7/dist-packages (from blessed)
Requirement already satisfied: wcwidth> = 0.1.4 in /usr/local/lib/python2.7/dist-packages (from blessed)
The directory '/home/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If installed pip with sudo, you May want sudo's -H flag.
The directory '/home/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. Check the permissions and owner of that directory. If installed pip with sudo, you may want sudo's -H flag
Requirement already satisfied: pyasn1 in /usr/lib/python2.7/dist-packages
Install the Pyinstaller
[*] Remove / opt / pyinstaller? [Y / n]

Not reinstalling ...

>

**Comment by Charliedean** [comment]
For a full reinstall you must enter 'y' when it asked to remove /opt/pyinstaller.

Can you run "uname -a" please

Thanks

**Comment by qsdj** [comment]
Linux ubuntu 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qsdj** [comment]
Remove /opt/pyinstaller? [Y/n] y
Still encountered the same mistake.

> Main Menu> 1

[*] Press Enter For Default Port (4444)
[*] Port>

[*] Press Enter To Get Local Ip Automatically (192.168.0.1)
[*] IP>
[*] IP SET AS 192.168.0.1
[*] PORT SET AS 4444

[*] Creating Payload using Pyinstaller ...
Mv: unable to get 'dist / payload.exe' file status (stat): no that file or directory

[*] Payload.exe Has Been Generated And Is Here Here: /home/root/winpayloads/Windows_Reverse_Shell.exe
Rm: can not delete 'dist': no that file or directory
Rm: can not delete 'build': no that file or directory
Rm: can not delete '* .spec': no that file or 

> directory

**Comment by Charliedean** [comment]
Hi,
In the lib dir. please edit the generatepayload.py file.

Look for the following code. and add the line surrounded in '**' in the code.

starts on line 68
```LOADING = Spinner('Generating Payload')
    while p.poll() == None:
        LOADING.Update()
        time.sleep(0.2)
    print '\r',
    sys.stdout.flush()

    payloadstderr = p.stderr.read()
    **print payloadstderr**
    if re.search('error', payloadstderr.lower()):
```

After this please try to generate a payload again.

**Comment by qsdj** [comment]
Thank you for your help, I am in accordance with your help to modify the code or encounter such a problem, I am ready to change the environment to Cali under the test.

> Ain Menu> 1

[*] Press Enter For Default Port (4444)
[*] Port>

[*] Press Enter To Get Local Ip Automatically (192.168.10.153)
[*] IP>
[*] IP SET AS 192.168.10.153
[*] PORT SET AS 4444

[*] Creating Payload using Pyinstaller ...
Wine: /home/root/.wine is not owned by you

Mv: unable to get 'dist / payload.exe' file status (stat): no that file or directory

[*] Payload.exe Has Been Generated And Is Here Here: /home/root/winpayloads/Windows_Reverse_Shell.exe
Rm: can not delete 'dist': no that file or directory
Rm: can not delete 'build': no that file or directory
Rm: can not delete '* .spec': no that file or directory

[*] Upload To Local Websever or (p) sexec? [Y] / p / n:
[*] Cleaning Up

> 68     LOADING = Spinner('Generating Payload')
 69     while p.poll() == None:
 70         LOADING.Update()
 71         time.sleep(0.2)
 72     print '\r',
 73     sys.stdout.flush()
 74 
 75     payloadstderr = p.stderr.read()
 76     print payloadstderr
 77     if re.search('error', payloadstderr.lower()):

**Comment by Charliedean** [comment]
Okay, so it looks like you either ran the installer or winpayloads as sudo.
Try running winecfg as a non root user and then winpayloads without sudo
