### ISSUE TITLE
problem when generating payloads "Internal error: early pywin32 import was introduced"

### ISSUE THREAD

**Issue by tueloup** [nccgroup/Winpayloads#36]
Hello

everyhting used to work previously, I just updated to latest version and now when generating a payload 

I get the following error

[*] Creating Payload using Pyinstaller...
[*] Error In Creating Payload... Exiting..

Internal error: early pywin32 import was introduced

I already tried to reinstall with ./setup.sh -r 

Do you have a clue ? Thanks in advance

**Comment by kerberos27** [comment]
Hello  

i had a same problem after installing Winpayloads by running ./setup.sh on terminal...  
but i was able to fix this problem by uninstalling wine!!!! by the way! i am using kali 2017.1_x64 :)
i uninstalled wine with commands below~~~

apt-get remove wine --purge              

rm -rf $HOME/.wine

rm -f $HOME/.config/menus/applications-merged/*wine*

rm -rf $HOME/.local/share/applications/wine

rm -f $HOME/.local/share/desktop-directories/*wine*

rm -f $HOME/.local/share/icons/wine_*.xpm

rm -f $HOME/.local/share/icons/*wine*

apt-get update

apt-get autoclean

apt-get clean

apt-get autoremove

apt-get update

**Comment by Charliedean** [comment]
Without wine winpayloads won't work. I will look in to this issue later as am busy now

**Comment by Charliedean** [comment]
Actually it seems like an issue with pyinstaller. https://stackoverflow.com/questions/45411660/internal-error-pywin32-with-pyinstaller
Try downgrading. I will update the setup soon so I downloads an older version

**Comment by kerberos27** [comment]
i think tuloup is getting the same error as me because the old wine is having a conflict with the new one when i ran the ./setup.sh  so i uninstalled wine to get a new wine installed but before i installed the new wine~~ its working fine now :) will show you the result as a video ~~ if you wish to see :)

**Comment by Charliedean** [comment]
Hi,

Should be fixed in latest commit (https://github.com/nccgroup/Winpayloads/commit/c5d207ff315f599d0ff0213280bc63668cc10cf3)
Please run ./setup.sh -r again


Thanks
Charlie
