### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by lordoracle** [nccgroup/Winpayloads#37]
Hi...

Problem with dependencies:

El paquete wine32 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

**Comment by Charliedean** [comment]
Hi, 

Could you make sure you have done a git pull?
Please could you translate to English for the next comment
Thanks
