### ISSUE TITLE
Does not generate payload files.

### ISSUE THREAD

**Issue by patxeco** [nccgroup/Winpayloads#38]
[*] Creating Payload using Pyinstaller...
mv: can not perform `stat 'on' <<dist/payload.exe>>: There is no directory file

[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_Shell.exe (But on this route there is nothing...)
rm: can not be deleted «dist»: There is no file or directory
rm: can not be deleted «build»: There is no file or directory
rm: can not be deleted «*.spec»: There is no file or directory

It may be because of a problem with wine?

I'm in a virtual machine
uname -a ->Linux Kali 4.0.0-kalil-686-pae #1 SMP Debian 4.0.4-1+kali2(2015-06-03) i686 GNU/Linux

thank you very much.

**Comment by Charliedean** [comment]
Hi,
Can you run with payloads with the -debug flag please.

Thanks

**Comment by patxeco** [comment]
Thanks for your speed, but how can i run payloads with the -debug flag ?
I'm sorry, I'm a little new

**Comment by Charliedean** [comment]
`./Winpayloads.py -debug`

**Comment by patxeco** [comment]
Charliedean the output is as follows:
[*] Creating Payload using Pyinstaller ...

1031 WARNING: Internal error: early pywin32 import was introduced

Traceback (most recent call last):

  File "/opt/pyinstaller/pyinstaller.py", line 15, in <module>

    Run ()
  File "Z: \ opt \ pyinstaller \ PyInstaller \ __ main__.py", line 62, in run

    Import PyInstaller.building.build_main

  File "Z: \ opt \ pyinstaller \ PyInstaller \ building \ build_main.py", line 32, in <module>

    From ..depend import bindepend

  File "Z: \ opt \ pyinstaller \ PyInstaller \ depend \ bindepend.py", line 18, in <module>

    Import pefile

ImportError: No module named pefile

Mv: can not perform `stat 'on' dist / payload.exe ': There is no file or directory


[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_Shell.exe

Rm: can not be deleted «dist»: There is no file or directory

Rm: can not delete «build»: There is no file or directory

Rm: can not be deleted «* .spec»: There is no file or directory

**Comment by Charliedean** [comment]
Okay re run the setup file with the -r flag
`./setup.sh -r`

**Comment by patxeco** [comment]
I did it but the result is the same ...

**Comment by Charliedean** [comment]
Please give the output or I cannot help you.

**Comment by patxeco** [comment]
[*] Creating Payload using Pyinstaller ...
1072 WARNING: Internal error: early pywin32 import was introduced
Traceback (most recent call last):
  File "/opt/pyinstaller/pyinstaller.py", line 15, in <module>
    Run ()
  File "Z: \ opt \ pyinstaller \ PyInstaller \ __ main__.py", line 62, in run
    Import PyInstaller.building.build_main
  File "Z: \ opt \ pyinstaller \ PyInstaller \ building \ build_main.py", line 32, in <module>
    From ..depend import bindepend
  File "Z: \ opt \ pyinstaller \ PyInstaller \ depend \ bindepend.py", line 18, in <module>
    Import pefile
ImportError: No module named pefile
Mv: can not perform `stat 'on' dist / payload.exe ': There is no file or directory
 
[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_Shell.exe
Rm: can not be deleted «dist»: There is no file or directory
Rm: can not delete «build»: There is no file or directory
Rm: can not be deleted «* .spec»: There is no file or directory

**Comment by Charliedean** [comment]
The output of setup -r

**Comment by patxeco** [comment]
The output of setup -r is very extensive you need all or something in particular.

**Comment by Charliedean** [comment]
Upload to pastebin please

**Comment by patxeco** [comment]
Sorry to have delayed and thanks for your patience.
https://pastebin.com/rCGAec1X

**Comment by Charliedean** [comment]
Try this:
`wine ~/.wine/drive_c/Python27/Scripts/pip.exe install pefile` 
Paste output please

**Comment by patxeco** [comment]
root@kali:/# wine /root/.wine/drive_c/Python27/Scripts/pip.exe install pefile
You are using pip version 7.0.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): pefile in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from pefile)

**Comment by Charliedean** [comment]
Hmm odd.
You shouldn't have any issues. 
Could you try to generate again?

**Comment by patxeco** [comment]
[*] Creating Payload using Pyinstaller...
4269 WARNING: Internal error: early pywin32 import was introduced
Traceback (most recent call last):
  File "/opt/pyinstaller/pyinstaller.py", line 15, in <module>
    run()
  File "Z:\opt\pyinstaller\PyInstaller\__main__.py", line 62, in run
    import PyInstaller.building.build_main
  File "Z:\opt\pyinstaller\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\pyinstaller\PyInstaller\depend\bindepend.py", line 27, in <module>
    from . import dylib, utils
  File "Z:\opt\pyinstaller\PyInstaller\depend\utils.py", line 25, in <module>
    from ..lib.modulegraph import util, modulegraph
  File "Z:\opt\pyinstaller\PyInstaller\lib\modulegraph\util.py", line 16, in <module>
    from ._compat import StringIO, BytesIO, get_instructions
  File "Z:\opt\pyinstaller\PyInstaller\lib\modulegraph\_compat.py", line 29, in <module>
    from dis3 import get_instructions
ImportError: No module named dis3
mv: no se puede efectuar `stat' sobre 'dist/payload.exe': No existe el fichero o el directorio

[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_Shell.exe
rm: no se puede borrar 'dist': No existe el fichero o el directorio
rm: no se puede borrar 'build': No existe el fichero o el directorio
rm: no se puede borrar '*.spec': No existe el fichero o el directorio

**Comment by Charliedean** [comment]
Okay try:
`wine ~/.wine/drive_c/Python27/Scripts/pip.exe install dis3`

**Comment by patxeco** [comment]
Charliedean you finally found the solution, thank you very much for your help and your time.

**Comment by Charliedean** [comment]
No problem,
Not sure why you had this issue
