### ISSUE TITLE
build error kali

### ISSUE THREAD

**Issue by Robiii97** [nccgroup/Winpayloads#39]
Hello.
iam trying to use this on my kali nethunter phone everyting went good untill i tried to build a payload.
it gives me the following error
http://imgur.com/a/RE2mK

**Comment by Charliedean** [comment]
https://github.com/nccgroup/Winpayloads/issues/21

**Comment by Robiii97** [comment]
It now gives me this. http://imgur.com/a/OqESo

It does not actually create the payload.

**Comment by Charliedean** [comment]
Please run with -debug 
`./winpayloads.py -debug`

**Comment by Robiii97** [comment]
Doesnt do anything no debug showing atall and still same error

**Comment by Charliedean** [comment]
Duplicate https://github.com/nccgroup/Winpayloads/issues/40

**Comment by Robiii97** [comment]
I redownloaded it re ran the setup still gives the same error.

**Comment by Charliedean** [comment]
Please help me help you.
Please show output of `./winpayloads.py -debug`

**Comment by Robiii97** [comment]
It doesnt give any debug output with that command?

**Comment by Charliedean** [comment]
Generate a payload while using that command

**Comment by Robiii97** [comment]
this it what it shows with debug command http://imgur.com/a/AYDcL

**Comment by PrettyBoyPBM** [comment]
I have the same error :c

**Comment by PrettyBoyPBM** [comment]
how can i fix it ?
