### ISSUE TITLE
payloads aren't working

### ISSUE THREAD

**Issue by marcelo321** [nccgroup/Winpayloads#44]
so i already test some payloads generators like chaos, fatrat, hercules and they all worked, but i tried the reverse_tcp and reverse_https but didn't work, dind't get  a session... any help why is this happening? do i need to isntall something else?

**Comment by marcelo321** [comment]
everything is perfect, but im not getting an stage.. i don't know whats wrong, any help?

**Comment by Charliedean** [comment]
This seems like a user error rather than an issue with winpayloads.
I cannot help you without any information
