### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by developerehis** [nccgroup/Winpayloads#47]
Here is the error i get even when i run /setup.sh -r
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\Python27\lib\runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "C:\Python27\lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Python27\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "C:\Python27\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Python27\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "C:\Python27\lib\ensurepip\__init__.py", line 9, in <module>
    import tempfile
  File "C:\Python27\lib\tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "C:\Python27\lib\random.py", line 885, in <module>
    _inst = Random()
  File "C:\Python27\lib\random.py", line 97, in __init__
    self.seed(x)
  File "C:\Python27\lib\random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
err:msi:ITERATE_Actions Execution halted, action L"UpdatePip" returned 1627
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
err:ole:CoGetClassObject class {00021401-0000-0000-c000-000000000046} not registered
err:ole:CoGetClassObject no class object {00021401-0000-0000-c000-000000000046} could be created for context 0x1
err:msi:ITERATE_CreateShortcuts CLSID_ShellLink not available
--2017-10-02 08:52:25--  http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe
Resolving www.voidspace.org.uk (www.voidspace.org.uk)... 207.38.86.245
Connecting to www.voidspace.org.uk (www.voidspace.org.uk)|207.38.86.245|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 972594 (950K) [application/x-msdownload]
Saving to: ‘pycrypto-2.6.win32-py2.7.exe’

pycrypto-2.6.win32- 100%[===================>] 949.80K   194KB/s    in 5.0s    

2017-10-02 08:52:30 (188 KB/s) - ‘pycrypto-2.6.win32-py2.7.exe’ saved [972594/972594]

Archive:  pycrypto-2.6.win32-py2.7.exe
warning [pycrypto-2.6.win32-py2.7.exe]:  196629 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  inflating: PLATLIB/pycrypto-2.6-py2.7.egg-info  
  inflating: PLATLIB/Crypto/pct_warnings.py  
  inflating: PLATLIB/Crypto/pct_warnings.pyc  
  inflating: PLATLIB/Crypto/__init__.py  
  inflating: PLATLIB/Crypto/__init__.pyc  
  inflating: PLATLIB/Crypto/Cipher/AES.py  
  inflating: PLATLIB/Crypto/Cipher/AES.pyc  
  inflating: PLATLIB/Crypto/Cipher/ARC2.py  
  inflating: PLATLIB/Crypto/Cipher/ARC2.pyc  
  inflating: PLATLIB/Crypto/Cipher/ARC4.py  
  inflating: PLATLIB/Crypto/Cipher/ARC4.pyc  
  inflating: PLATLIB/Crypto/Cipher/blockalgo.py  
  inflating: PLATLIB/Crypto/Cipher/blockalgo.pyc  
  inflating: PLATLIB/Crypto/Cipher/Blowfish.py  
  inflating: PLATLIB/Crypto/Cipher/Blowfish.pyc  
  inflating: PLATLIB/Crypto/Cipher/CAST.py  
  inflating: PLATLIB/Crypto/Cipher/CAST.pyc  
  inflating: PLATLIB/Crypto/Cipher/DES.py  
  inflating: PLATLIB/Crypto/Cipher/DES.pyc  
  inflating: PLATLIB/Crypto/Cipher/DES3.py  
  inflating: PLATLIB/Crypto/Cipher/DES3.pyc  
  inflating: PLATLIB/Crypto/Cipher/PKCS1_OAEP.py  
  inflating: PLATLIB/Crypto/Cipher/PKCS1_OAEP.pyc  
  inflating: PLATLIB/Crypto/Cipher/PKCS1_v1_5.py  
  inflating: PLATLIB/Crypto/Cipher/PKCS1_v1_5.pyc  
  inflating: PLATLIB/Crypto/Cipher/XOR.py  
  inflating: PLATLIB/Crypto/Cipher/XOR.pyc  
  inflating: PLATLIB/Crypto/Cipher/_AES.pyd  
  inflating: PLATLIB/Crypto/Cipher/_ARC2.pyd  
  inflating: PLATLIB/Crypto/Cipher/_ARC4.pyd  
  inflating: PLATLIB/Crypto/Cipher/_Blowfish.pyd  
  inflating: PLATLIB/Crypto/Cipher/_CAST.pyd  
  inflating: PLATLIB/Crypto/Cipher/_DES.pyd  
  inflating: PLATLIB/Crypto/Cipher/_DES3.pyd  
  inflating: PLATLIB/Crypto/Cipher/_XOR.pyd  
  inflating: PLATLIB/Crypto/Cipher/__init__.py  
  inflating: PLATLIB/Crypto/Cipher/__init__.pyc  
  inflating: PLATLIB/Crypto/Hash/hashalgo.py  
  inflating: PLATLIB/Crypto/Hash/hashalgo.pyc  
  inflating: PLATLIB/Crypto/Hash/HMAC.py  
  inflating: PLATLIB/Crypto/Hash/HMAC.pyc  
  inflating: PLATLIB/Crypto/Hash/MD2.py  
  inflating: PLATLIB/Crypto/Hash/MD2.pyc  
  inflating: PLATLIB/Crypto/Hash/MD4.py  
  inflating: PLATLIB/Crypto/Hash/MD4.pyc  
  inflating: PLATLIB/Crypto/Hash/MD5.py  
  inflating: PLATLIB/Crypto/Hash/MD5.pyc  
  inflating: PLATLIB/Crypto/Hash/RIPEMD.py  
  inflating: PLATLIB/Crypto/Hash/RIPEMD.pyc  
  inflating: PLATLIB/Crypto/Hash/SHA.py  
  inflating: PLATLIB/Crypto/Hash/SHA.pyc  
  inflating: PLATLIB/Crypto/Hash/SHA224.py  
  inflating: PLATLIB/Crypto/Hash/SHA224.pyc  
  inflating: PLATLIB/Crypto/Hash/SHA256.py  
  inflating: PLATLIB/Crypto/Hash/SHA256.pyc  
  inflating: PLATLIB/Crypto/Hash/SHA384.py  
  inflating: PLATLIB/Crypto/Hash/SHA384.pyc  
  inflating: PLATLIB/Crypto/Hash/SHA512.py  
  inflating: PLATLIB/Crypto/Hash/SHA512.pyc  
  inflating: PLATLIB/Crypto/Hash/_MD2.pyd  
  inflating: PLATLIB/Crypto/Hash/_MD4.pyd  
  inflating: PLATLIB/Crypto/Hash/_RIPEMD160.pyd  
  inflating: PLATLIB/Crypto/Hash/_SHA224.pyd  
  inflating: PLATLIB/Crypto/Hash/_SHA256.pyd  
  inflating: PLATLIB/Crypto/Hash/_SHA384.pyd  
  inflating: PLATLIB/Crypto/Hash/_SHA512.pyd  
  inflating: PLATLIB/Crypto/Hash/__init__.py  
  inflating: PLATLIB/Crypto/Hash/__init__.pyc  
  inflating: PLATLIB/Crypto/Protocol/AllOrNothing.py  
  inflating: PLATLIB/Crypto/Protocol/AllOrNothing.pyc  
  inflating: PLATLIB/Crypto/Protocol/Chaffing.py  
  inflating: PLATLIB/Crypto/Protocol/Chaffing.pyc  
  inflating: PLATLIB/Crypto/Protocol/KDF.py  
  inflating: PLATLIB/Crypto/Protocol/KDF.pyc  
  inflating: PLATLIB/Crypto/Protocol/__init__.py  
  inflating: PLATLIB/Crypto/Protocol/__init__.pyc  
  inflating: PLATLIB/Crypto/PublicKey/DSA.py  
  inflating: PLATLIB/Crypto/PublicKey/DSA.pyc  
  inflating: PLATLIB/Crypto/PublicKey/ElGamal.py  
  inflating: PLATLIB/Crypto/PublicKey/ElGamal.pyc  
  inflating: PLATLIB/Crypto/PublicKey/pubkey.py  
  inflating: PLATLIB/Crypto/PublicKey/pubkey.pyc  
  inflating: PLATLIB/Crypto/PublicKey/RSA.py  
  inflating: PLATLIB/Crypto/PublicKey/RSA.pyc  
  inflating: PLATLIB/Crypto/PublicKey/_DSA.py  
  inflating: PLATLIB/Crypto/PublicKey/_DSA.pyc  
  inflating: PLATLIB/Crypto/PublicKey/_RSA.py  
  inflating: PLATLIB/Crypto/PublicKey/_RSA.pyc  
  inflating: PLATLIB/Crypto/PublicKey/_slowmath.py  
  inflating: PLATLIB/Crypto/PublicKey/_slowmath.pyc  
  inflating: PLATLIB/Crypto/PublicKey/__init__.py  
  inflating: PLATLIB/Crypto/PublicKey/__init__.pyc  
  inflating: PLATLIB/Crypto/Random/random.py  
  inflating: PLATLIB/Crypto/Random/random.pyc  
  inflating: PLATLIB/Crypto/Random/_UserFriendlyRNG.py  
  inflating: PLATLIB/Crypto/Random/_UserFriendlyRNG.pyc  
  inflating: PLATLIB/Crypto/Random/__init__.py  
  inflating: PLATLIB/Crypto/Random/__init__.pyc  
  inflating: PLATLIB/Crypto/Random/Fortuna/FortunaAccumulator.py  
  inflating: PLATLIB/Crypto/Random/Fortuna/FortunaAccumulator.pyc  
  inflating: PLATLIB/Crypto/Random/Fortuna/FortunaGenerator.py  
  inflating: PLATLIB/Crypto/Random/Fortuna/FortunaGenerator.pyc  
  inflating: PLATLIB/Crypto/Random/Fortuna/SHAd256.py  
  inflating: PLATLIB/Crypto/Random/Fortuna/SHAd256.pyc  
  inflating: PLATLIB/Crypto/Random/Fortuna/__init__.py  
  inflating: PLATLIB/Crypto/Random/Fortuna/__init__.pyc  
  inflating: PLATLIB/Crypto/Random/OSRNG/fallback.py  
  inflating: PLATLIB/Crypto/Random/OSRNG/fallback.pyc  
  inflating: PLATLIB/Crypto/Random/OSRNG/nt.py  
  inflating: PLATLIB/Crypto/Random/OSRNG/nt.pyc  
  inflating: PLATLIB/Crypto/Random/OSRNG/posix.py  
  inflating: PLATLIB/Crypto/Random/OSRNG/rng_base.py  
  inflating: PLATLIB/Crypto/Random/OSRNG/rng_base.pyc  
  inflating: PLATLIB/Crypto/Random/OSRNG/winrandom.pyd  
  inflating: PLATLIB/Crypto/Random/OSRNG/__init__.py  
  inflating: PLATLIB/Crypto/Random/OSRNG/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/st_common.py  
  inflating: PLATLIB/Crypto/SelfTest/st_common.pyc  
  inflating: PLATLIB/Crypto/SelfTest/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/common.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/common.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_AES.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_AES.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_ARC2.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_ARC2.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_ARC4.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_ARC4.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_Blowfish.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_Blowfish.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_CAST.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_CAST.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_DES.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_DES.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_DES3.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_DES3.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_pkcs1_15.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_pkcs1_15.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_pkcs1_oaep.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_XOR.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/test_XOR.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Cipher/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/common.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/common.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_HMAC.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_HMAC.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_MD2.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_MD2.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_MD4.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_MD4.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_MD5.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_MD5.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_RIPEMD.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_RIPEMD.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA224.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA224.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA256.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA256.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA384.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA384.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA512.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/test_SHA512.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Hash/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Hash/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_AllOrNothing.py  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_AllOrNothing.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_chaffing.py  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_chaffing.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_KDF.py  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_rfc1751.py  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/test_rfc1751.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Protocol/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_DSA.py  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_DSA.pyc  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_ElGamal.py  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_ElGamal.pyc  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_importKey.py  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_importKey.pyc  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_RSA.py  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/test_RSA.pyc  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/PublicKey/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/test_random.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/test_random.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/test_rpoolcompat.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/test_rpoolcompat.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/test_SHAd256.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/Fortuna/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_fallback.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_fallback.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_generic.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_generic.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_nt.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_nt.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_posix.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_winrandom.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/test_winrandom.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Random/OSRNG/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Signature/test_pkcs1_15.py  
  inflating: PLATLIB/Crypto/SelfTest/Signature/test_pkcs1_15.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Signature/test_pkcs1_pss.py  
  inflating: PLATLIB/Crypto/SelfTest/Signature/test_pkcs1_pss.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Signature/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Signature/__init__.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_asn1.py  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_Counter.py  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_Counter.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_number.py  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_number.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_winrandom.py  
  inflating: PLATLIB/Crypto/SelfTest/Util/test_winrandom.pyc  
  inflating: PLATLIB/Crypto/SelfTest/Util/__init__.py  
  inflating: PLATLIB/Crypto/SelfTest/Util/__init__.pyc  
  inflating: PLATLIB/Crypto/Signature/PKCS1_PSS.py  
  inflating: PLATLIB/Crypto/Signature/PKCS1_PSS.pyc  
  inflating: PLATLIB/Crypto/Signature/PKCS1_v1_5.py  
  inflating: PLATLIB/Crypto/Signature/PKCS1_v1_5.pyc  
  inflating: PLATLIB/Crypto/Signature/__init__.py  
  inflating: PLATLIB/Crypto/Signature/__init__.pyc  
  inflating: PLATLIB/Crypto/Util/asn1.py  
  inflating: PLATLIB/Crypto/Util/asn1.pyc  
  inflating: PLATLIB/Crypto/Util/Counter.py  
  inflating: PLATLIB/Crypto/Util/Counter.pyc  
  inflating: PLATLIB/Crypto/Util/number.py  
  inflating: PLATLIB/Crypto/Util/number.pyc  
  inflating: PLATLIB/Crypto/Util/py21compat.py  
  inflating: PLATLIB/Crypto/Util/py3compat.py  
  inflating: PLATLIB/Crypto/Util/py3compat.pyc  
  inflating: PLATLIB/Crypto/Util/randpool.py  
  inflating: PLATLIB/Crypto/Util/randpool.pyc  
  inflating: PLATLIB/Crypto/Util/RFC1751.py  
  inflating: PLATLIB/Crypto/Util/RFC1751.pyc  
  inflating: PLATLIB/Crypto/Util/strxor.pyd  
  inflating: PLATLIB/Crypto/Util/winrandom.py  
  inflating: PLATLIB/Crypto/Util/winrandom.pyc  
  inflating: PLATLIB/Crypto/Util/_counter.pyd  
  inflating: PLATLIB/Crypto/Util/_number_new.py  
  inflating: PLATLIB/Crypto/Util/_number_new.pyc  
  inflating: PLATLIB/Crypto/Util/__init__.py  
  inflating: PLATLIB/Crypto/Util/__init__.pyc  
--2017-10-02 08:52:31--  https://download.microsoft.com/download/1/1/1/1116b75a-9ec3-481a-a3c8-1777b5381140/vcredist_x86.exe
Resolving download.microsoft.com (download.microsoft.com)... 23.212.232.197, 2a02:26f0:7400:193::e59, 2a02:26f0:7400:189::e59
Connecting to download.microsoft.com (download.microsoft.com)|23.212.232.197|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1821192 (1.7M) [application/octet-stream]
Saving to: ‘vcredist_x86.exe’

vcredist_x86.exe    100%[===================>]   1.74M   189KB/s    in 9.4s    

2017-10-02 08:52:41 (189 KB/s) - ‘vcredist_x86.exe’ saved [1821192/1821192]

^C--2017-10-02 08:54:17--  https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/pywin32-220.win32-py2.7.exe/download
Resolving sourceforge.net (sourceforge.net)... 216.34.181.60
Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20220/pywin32-220.win32-py2.7.exe?r=&ts=1506948859&use_mirror=netix [following]
--2017-10-02 08:54:19--  https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20220/pywin32-220.win32-py2.7.exe?r=&ts=1506948859&use_mirror=netix
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:443... connected.

Installation of vcredist_x86.exe give extraction of error

What can i do?

**Comment by Charliedean** [comment]
Hi,
It looks like you pressed CTRL + C. Could this be the reason?

Here is the escape sequence for CTRL c found in the code you pasted:
`2017-10-02 08:52:41 (189 KB/s) - ‘vcredist_x86.exe’ saved [1821192/1821192]^C--2017-10-02 08:54:17--`

**Comment by developerehis** [comment]
But how can this b? i have ran set more than 10 times in the last one week.

**Comment by Charliedean** [comment]
Is there any error when generating a payload?

**Comment by developerehis** [comment]
yes and below is the code:

[*] Creating Payload using Pyinstaller...
mv: cannot stat 'dist/payload.exe': No such file or directory

[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_HTTPS.exe
rm: cannot remove 'dist': No such file or directory
rm: cannot remove 'build': No such file or directory
rm: cannot remove '*.spec': No such file or directory

and when i check the path /root/winpayloads/Windows_Meterpreter_Reverse_HTTPS.exe there is nothing there

**Comment by Charliedean** [comment]
Sorry, run winpayloads with -debug please and try again

**Comment by developerehis** [comment]
Thanks for your prompt response. I get error:
root@kali:~/Winpayloads# winpayloads -debug
bash: winpayloads: command not found

Kindly help with correct command format

**Comment by Charliedean** [comment]
Well it would be ./winpayloads.py -debug

**Comment by developerehis** [comment]
still not generating below is the errror:
[*] Creating Payload using Pyinstaller...
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
err:module:import_dll Library pywintypes27.dll (which is needed by L"C:\\Python27\\lib\\site-packages\\win32\\win32api.pyd") not found
Traceback (most recent call last):
  File "/opt/pyinstaller/pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\pyinstaller\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\pyinstaller\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\pyinstaller\PyInstaller\depend\bindepend.py", line 26, in <module>
    from . import dylib, utils
  File "Z:\opt\pyinstaller\PyInstaller\depend\utils.py", line 25, in <module>
    from ..lib.modulegraph import modulegraph
  File "Z:\opt\pyinstaller\PyInstaller\lib\modulegraph\modulegraph.py", line 18, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
mv: cannot stat 'dist/payload.exe': No such file or directory

[*] Payload.exe Has Been Generated And Is Located Here: /root/winpayloads/Windows_Meterpreter_Reverse_HTTPS.exe
rm: cannot remove 'dist': No such file or directory
rm: cannot remove 'build': No such file or directory
rm: cannot remove '*.spec': No such file or directory

**Comment by Charliedean** [comment]
Hi,
Please try `apt purge wine wine32`
Then run `./setup.sh -r` again please

**Comment by developerehis** [comment]
I still get the reror after downloading vcredist_x86.exe:
vcredist_x86.exe    100%[===================>]   1.74M  41.5KB/s    in 65s     

2017-10-03 06:40:50 (27.5 KB/s) - ‘vcredist_x86.exe’ saved [1821192/1821192]

the error is "unable to finds a volume for file extraction, please verify that you have proper permission"

can this be from my kali linux installation?
