### ISSUE TITLE
No persistence?

### ISSUE THREAD

**Issue by brinerband** [nccgroup/Winpayloads#51]
Sorry for noob question but where is the persistence script?

**Comment by Charliedean** [comment]
Did you check out the wiki and the video?

**Comment by brinerband** [comment]
Yes but i dont see persist.ps1 file ? 
Im really sorry for this questions ..
And thank you on your replay

**Comment by Charliedean** [comment]
What do you need this exact file for? When metasploit opens it automatically uses the persist.ps1 file. It gets saved to the current working directory and deleted when winpayloads exits.
