### ISSUE TITLE
payload not create show message payload located in /root/

### ISSUE THREAD

**Issue by krishnenduash** [nccgroup/Winpayloads#54]
reinstall  2 times same problem. in 64bit new version of kalilinux

few month ago i used 32 bit then work perfect..but not.

please fix the problem

![kali 2017 3 64-2018-01-31-18-11-11](https://user-images.githubusercontent.com/30100922/35609701-776582f8-06b2-11e8-859e-e001342127ed.png)
![kali 2017 3 64-2018-01-31-18-10-02](https://user-images.githubusercontent.com/30100922/35609719-8b0918a6-06b2-11e8-839c-6c36e6fbab27.png)
![kali 2017 3 64-2018-01-31-18-49-11](https://user-images.githubusercontent.com/30100922/35611518-5c65434c-06b9-11e8-8083-6cbe1cc765fe.png)

**Comment by Charliedean** [comment]
Hi,

Can you please run winpayloads with the -debug flag and let me know the output.
Thanks
