### ISSUE TITLE
can't generate payload :'(

### ISSUE THREAD

**Issue by rayenmessaoudi** [nccgroup/Winpayloads#55]
[*] Creating Payload using Pyinstaller...
mv: cannot stat 'dist/payload.exe': No such file or directory

[*] Payload.exe Has Been Generated And Is Located Here: /home/psycor/winpayloads/Windows_Reverse_Shell.exe
rm: cannot remove 'dist': No such file or directory
rm: cannot remove 'build': No such file or directory
rm: cannot remove '*.spec': No such file or directory

**Comment by Charliedean** [comment]
Hi,

Please run winpayloads with the `-debug` flag and try again. 
Post the output here

Thanks
Charlie

**Comment by rayenmessaoudi** [comment]
[*] Creating Payload using Pyinstaller...
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored
Traceback (most recent call last):
  File "/opt/pyinstaller/pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\pyinstaller\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\pyinstaller\PyInstaller\building\build_main.py", line 34, in <module>
    from .api import PYZ, EXE, COLLECT, MERGE
  File "Z:\opt\pyinstaller\PyInstaller\building\api.py", line 38, in <module>
    from PyInstaller.utils.win32 import winmanifest, icon, versioninfo, winresource
  File "Z:\opt\pyinstaller\PyInstaller\utils\win32\versioninfo.py", line 18, in <module>
    from ...lib import pefile
  File "Z:\opt\pyinstaller\PyInstaller\lib\pefile.py", line 26, in <module>
    from past.builtins import cmp, long
ImportError: No module named past.builtins
fixme:msvcrt:__clean_type_info_names_internal (0x1e3b304c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x113a498) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1d1b5210) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e8d8088) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e7ba8c4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x10139568) stub
fixme:msvcrt:__clean_type_info_names_internal (0x43ca30) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e24e5b8) stub
mv: cannot stat 'dist/payload.exe': No such file or directory

[*] Payload.exe Has Been Generated And Is Located Here: /home/user/winpayloads/Windows_Reverse_Shell.exe
rm: cannot remove 'dist': No such file or directory
rm: cannot remove 'build': No such file or directory
rm: cannot remove '*.spec': No such file or directory

**Comment by Charliedean** [comment]
Hi,
Please try to rerun the setup with the `-r` flag

**Comment by rayenmessaoudi** [comment]
new error 

wine: /home/user/.wine is not owned by you
mv: cannot stat 'dist/payload.exe': No such file or directory

[*] Payload.exe Has Been Generated And Is Located Here: /home/user/winpayloads/Windows_Meterpreter_Reverse_HTTPS.exe
rm: cannot remove 'dist': No such file or directory
rm: cannot remove 'build': No such file or directory
rm: cannot remove '*.spec': No such file or directory

**Comment by Charliedean** [comment]
What distro are you using? - seems like a permission error with wine. Try to run as root?

**Comment by rayenmessaoudi** [comment]
already runnig as root,
i am using backbox 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by Charliedean** [comment]
Okay, the install script works perfectly for Kali, but for Ubuntu it can have some issues.
I will get back to you on this issue as i will have to manually install winpayloads on a ubuntu vm to test.

for now, you could try to su to root and run the install script with -r. After installation run winpayloads when su'ed to root user

Charlie

**Comment by ddgdfl** [comment]
i got the same problem,and...OS is kali

**Comment by zupd** [comment]
Same problem. os is kali
