### ISSUE TITLE
error while running ./WinPayloads.py

### ISSUE THREAD

**Issue by xuniltra** [nccgroup/Winpayloads#57]
error!
I have run setup.sh and it runs fine. . however when I run ./WinPayloads.py I get this error:

**root@kali:~/Desktop/Winpayloads#** **./WinPayloads.py** 
Traceback (most recent call last):
  File "./WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/Desktop/Winpayloads/lib/main.py", line 8, in <module>
    import blessed
ImportError: No module named blessed

Please give me a solution

**Comment by Charliedean** [comment]
Try pip install blessed

**Comment by xuniltra** [comment]
I have installed it. .
when run WinPayloads get again the same error

**root@kali:~/Desktop/Winpayloads# pip install blessed**
Requirement already satisfied: blessed in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from blessed)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.6/dist-packages (from blessed)

**root@kali:~/Desktop/Winpayloads# python WinPayloads.py** 
Traceback (most recent call last):
  File "WinPayloads.py", line 2, in <module>
    from lib.main import *
  File "/root/Desktop/Winpayloads/lib/main.py", line 8, in <module>
    import blessed
ImportError: No module named blessed

What happened. please give me a solution?
I use Kali Linux.

**Comment by pyinal** [comment]
Maybe you should try pip2.7 install blessed

**Comment by xuniltra** [comment]
Hi @pyinal the command does not exist

**root@kali:~# pip2.7 install blessed**
bash: pip2.7: command not found

**Comment by xuniltra** [comment]
okay, i've fixed that. .
reality in **python2.7** i have nothing blessed. .. .
when i run **pip install blessed**. . it turns blessed it is installed in **python3.6** not in **python27. .**
so, to fix it. .
**pip2 install blessed**
