### ISSUE TITLE
Error .git repository

### ISSUE THREAD

**Issue by l3m3ssag3r** [nccgroup/Winpayloads#63]
fatal: neither this nor any of its parent directories is a git: .git repository
Traceback (most recent call last):
   File "./WinPayloads.py", line 23, in <module>
     gitrev = subprocess.check_output (['git', 'rev-parse', 'HEAD']). rstrip ()
   File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
     raise CalledProcessError (retcode, cmd, output = output)
subprocess.CalledProcessError: Command '[' git ',' rev-parse ',' HEAD ']' returned non-zero exit status 128

**Comment by Charliedean** [comment]
Are you running this from the winpayloads directory?
Manual or docker install?
The error is because your current directory does not seem to contain a .git or the permissions are wrong.

**Comment by l3m3ssag3r** [comment]
Yes, I use it from the WinPayloads directory.
To install it I did: apt-get install docker, then in the Winpayload folder:
./setup.sh
./ Winpayload.py
Thank you for correcting me if I made a mistake or show me how to install it from the docker

**Comment by l3m3ssag3r** [comment]
problem solved.
you had to follow the installation normally without having to download the zip file.
# git clone https://github.com/nccgroup/Winpayloads.git
and it's good...
